name: Publish Nightly

on:
  schedule:
    - cron:  '0 7 * * *'
  repository_dispatch:
    types: publish-nightly

jobs:
  build:
    runs-on: ubuntu-latest
    name: Runs some tests...

    if: github.actor == github.event.repository.owner.login
    steps:

    - name: Check out code
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.OWNER }}

    - name: Docker action step
      id: mmcdocker
      uses: mchirico/sshproxy-action@v1
      with:
        id_rsa: ${{ secrets.SSH_PRIVATE_KEY }}
        user: ${{ secrets.USER }}
        server: ${{ secrets.SERVER }}
      env: # For ssh
        INPUT_MILLISECONDS: 500
